import os
from dotenv import load_dotenv

load_dotenv()

TG_TOKEN = os.getenv("TG_TOKEN")
TG_AIO_TOKEN = os.getenv("TG_AIO_TOKEN")
PROXY_API_TOKEN = os.getenv("PROXY_API_TOKEN")
PROXY_API = os.getenv("PROXY_API")

IMG1 = {
    'gpt': 'AgACAgIAAxkBAAILg2e60X46FBRho_EO760le4r55V0fAAKO8jEbkrLQSaNJrChaWS1YAQADAgADeAADNgQ',
    'quiz': 'AgACAgIAAxkBAAILhGe60b5aQtFBRKeHfY2j-8Y1AAFY4gACqugxG3v72EmtZjzKY8Ip9AEAAwIAA3gAAzYE',
    'random': 'AgACAgIAAxkBAAILhWe60dhf9ZkeTOAea8-3HdPy3iRYAAKQ8jEbkrLQSX1-KJ6tKY_fAQADAgADeQADNgQ',
    'talk': 'AgACAgIAAxkBAAILhme60fbI1Embhat4dZjW-FDOCxMqAAKR8jEbkrLQSWhyA6cRoh2NAQADAgADeAADNgQ',
    'talk_cobain': 'AgACAgIAAxkBAAILh2e60iHxKjdoJhavFwUmDfffEsSWAAKT8jEbkrLQSU0mRC08mVciAQADAgADeAADNgQ',
    'talk_hawking': 'AgACAgIAAxkBAAILiGe60ki24-kv4oZMZZK_qAufBcTwAAKW8jEbkrLQSX1N7CDexrfHAQADAgADeQADNgQ',
    'talk_nietzsche': 'AgACAgIAAxkBAAILiWe60msElp7mjdlZormmNuo930ErAAKf8jEbkrLQSUmLj_EhW36KAQADAgADeQADNgQ',
    'talk_queen': 'AgACAgIAAxkBAAILime60pFshCsbDhxbN3pwkEvzKu-JAALC8jEbkrLQSYnmSSAu8kLLAQADAgADeQADNgQ',
    'talk_tolkien': 'AgACAgIAAxkBAAILi2e60sp5IoVHs6plG1zzqpJMYoZmAAKv6DEbe_vYSesPA7rvTipOAQADAgADeQADNgQ',
}

IMG = {
    'gpt': 'AgACAgIAAxkBAAMRZ74hYM8qJk249hfHVrB-7SSN3kwAAq3rMRuLSflJEqdGQYdyIbYBAAMCAAN4AAM2BA',
    'quiz': 'AgACAgIAAxkBAAMTZ74iIOehz3ASKPPH-ToRcFiLIW8AAlDsMRvZGvBJVHNZcbsSl7kBAAMCAAN4AAM2BA',
    'random': 'AgACAgIAAxkBAAMUZ74iNlPwvGPHNlJ70mx5HEJnB1kAAlHsMRvZGvBJEMZs8kHKdYoBAAMCAAN5AAM2BA',
    'talk': 'AgACAgIAAxkBAAMVZ74iSrBqTBtjYRKMYKJCVZbXuVAAAlLsMRvZGvBJFFly2AJAwnoBAAMCAAN4AAM2BA',
    'talk_cobain': 'AgACAgIAAxkBAAMWZ74iX6Ho4BWmswABt6SjNq3bx-w0AAJT7DEb2RrwSQABWKOrd06pNAEAAwIAA3gAAzYE',
    'talk_hawking': 'AgACAgIAAxkBAAMXZ74ien6RVPN07nvfIbhGZydu10UAAlTsMRvZGvBJFOPV1v5BU-wBAAMCAAN5AAM2BA',
    'talk_nietzsche': 'AgACAgIAAxkBAAMYZ74ijaHNrQlWyGZR4sZYd1UOy8cAAlbsMRvZGvBJVySnvKuZH8ABAAMCAAN5AAM2BA',
    'talk_queen': 'AgACAgIAAxkBAAMZZ74inIH87LRbefhO98qIRqzRMmEAAlfsMRvZGvBJVUKPJ13Tj5IBAAMCAAN5AAM2BA',
    'talk_tolkien': 'AgACAgIAAxkBAAMaZ74irJnWl5P_ZkT5-hFr0qSeGeMAAlvsMRvZGvBJUzdh3CoDLK4BAAMCAAN5AAM2BA',
}